

//Login
export const LOGIN_FETCHING_DATA = 'LOGIN_FETCHING_DATA';
export const LOGIN_FETCHING_DATA_SUCCESS = 'LOGIN_FETCHING_DATA_SUCCESS';
export const LOGIN_FETCHING_DATA_ERROR = 'LOGIN_FETCHING_DATA_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_DATA = 'LOGOUT_DATA';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';